### ISSUE TITLE
Preferences does not open

### ISSUE THREAD

**Issue by yochananmarqos** [mijorus/smile#25]
Using 2.0.0:

```
Emoji list creation took 87.236173ms
Traceback (most recent call last):
  File "/usr/share/smile/smile/main.py", line 60, in <lambda>
    self.create_action("preferences", lambda w, e: Settings(self.application_id))
  File "/usr/share/smile/smile/Settings.py", line 59, in __init__
    self.custom_tags_rows = self.create_custom_tags_list()
  File "/usr/share/smile/smile/Settings.py", line 103, in create_custom_tags_list
    rows.append(self.empty_list_label)
AttributeError: 'Settings' object has no attribute 'empty_list_label'
```

**Comment by mijorus** [comment]
should be fixed with 2.0.1, sorry for that

**Comment by yochananmarqos** [comment]
Yes, it's fixed now. However, when closing the preferences I see this:

```
Traceback (most recent call last):
  File "/usr/share/smile/smile/Settings.py", line 197, in on_window_close
    set_custom_tags(row.hexcode, row.__entry.get_text())
AttributeError: 'ActionRow' object has no attribute 'hexcode'
```

**Comment by mijorus** [comment]
last fix I promise XD

**Comment by mijorus** [comment]
should be fixed with the latest tag

**Comment by yochananmarqos** [comment]
Thankee sai! :cowboy_hat_face:
