### ISSUE TITLE
Smile doesn't want to open.

### ISSUE THREAD

**Issue by AndriuxDev** [mijorus/smile#50]
Traceback (most recent call last):
  File "/app/share/smile/smile/main.py", line 61, in do_activate
    self.window = Picker(application=self)
  File "/app/share/smile/smile/Picker.py", line 41, in __init__
    super().__init__(title="Smile", resizable=True, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

What can I do?

**Comment by mijorus** [comment]
Are you using the flatpak version?

**Comment by mijorus** [comment]
I the same issue on a VM when switching from x to wayland. It that what's happening here?
