### ISSUE TITLE
won't open on Fedora 38 (flatpak version)

### ISSUE THREAD

**Issue by davidM-tugraz** [mijorus/smile#60]
Hello,
when I try to launch the app nothing happens. When launching via a terminal I get the following output:

```[david@zbook-firefly14-g7 ~]$ flatpak run it.mijorus.smile 
Traceback (most recent call last):
  File "/app/share/smile/smile/main.py", line 59, in do_activate
    self.window = Picker(application=self)
  File "/app/share/smile/smile/Picker.py", line 105, in __init__
    self.refresh_emoji_list()
  File "/app/share/smile/smile/Picker.py", line 209, in refresh_emoji_list
    self.emoji_list.remove_all()
AttributeError: 'FlowBox' object has no attribute 'remove_all'
^C
[david@zbook-firefly14-g7 ~]$ 
```

System:
Fedora 38
Gnome 44.5
Wayland
Flatpak 1.15.4

**Comment by VortexAcherontic** [comment]
Updated just now on openSUSE Aeon. Works for me now.

**Comment by davidM-tugraz** [comment]
Just got the update and it works again. Thanks.
