### ISSUE TITLE
Arch - Gnome 42 - "ValueError: Namespace Wnck not available"

### ISSUE THREAD

**Issue by srirangan** [mijorus/smile#9]
Is it just me?

```
❯ flatpak run it.mijorus.smile
Traceback (most recent call last):
  File "/app/bin/smile", line 41, in <module>
    from smile import main
  File "/app/share/smile/smile/main.py", line 5, in <module>
    from .Picker import Picker
  File "/app/share/smile/smile/Picker.py", line 30, in <module>
    gi.require_version('Wnck', '3.0')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
```

**Comment by mijorus** [comment]
Omg, shame on me. I forgot to sync the flatpak json file with the flatpak repo. An update as be pushed now, should be available in the next few hours

**Comment by mijorus** [comment]
@srirangan  I can confirm that the update was pushed to Flathub successfully. It should be available now. 

Please let me know if the problem persists after the update.

**Comment by srirangan** [comment]
Updated and works great, thanks @mijorus !
